spring:
  application:
    name: gateway-service
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
        defaultZone: http://discovery:2001/eureka/
zuul:
  routes:
    service-provider:
      path: /user-service/**
      serviceId: service-provider
