server:
  port: 80
  context-path: /
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: student-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
