server:
  port: 1001

 # 数据源配置
spring:
  application:
    name: service-provider
  profiles:
    active: local
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: service-provider  #客户端服务名
    instance-id: service-provider:1001XX22 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
       defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
#      defaultZone: http://eureka2001.java1234.com:2001/eureka/,http://eureka2002.java1234.com:2002/eureka/,http://eureka2003.java1234.com:2003/eureka/ # 集群
swagger:
  base-package: com.java1234.controller